### ISSUE TITLE
My bug finds

### ISSUE THREAD

**Issue by hyrule1989** [gameboy9/DW4RandoHacker#1]
Bugs I've found so far:

Solo Hero challenge didn't lose character at Gardenbur, may have resulted in loss of wagon that caused softlock at World Tree

Character chapter placement and chapter 5 pickup order randomization seems to still not work with picking up Brey only in Mintos (even though the character I picked up was actually Brey!), and when I picked up the two other characters, I only collected 1.  At that point I still didn't have Hero or Alena, and only the Ragnar placement left to find.

Related to above, you may want to create a backup plan, as I could not actually get to the Ragnar placement because I did not have the Thief Key to access the Magic Key (It was still on my Hero), and thus softlocked the game.

**Comment by gameboy9** [comment]
I will take a look at the first two paragraphs with no questions right now.

With the third paragraph, did you check the first treasure chest in the Aktemto Mine in Chapter 4?  The Magic Key is there.  However, the enhancement I want to make is to change it so that the solo hero can knock down the door in Chapter 4 instead of Orin.  (Which is why the Magic Key was placed in that treasure chest in the first place)

**Comment by hyrule1989** [comment]
I forgot to mention about that.  I picked up the chest in Chapter 4, and it was still Mystic Acorns.  Maybe that's only tied to the solo challenge?  I didn't go back to check it in Chapter 5 since I assumed it would still be already opened, and unfortunately have since deleted the file.

Another thing, if you can, you might want to see about taking Linguar out of possible random battles.  I just remembered I ran into him on the map, but it was 4 of him, and then each tried to split.  Next thing I know I have 7 Linguars, 3 of which aren't on the screen and may or may not be real.  I should feel thankful that I had 1 group of 4 and 3 groups of 1 instead of 4 groups of 4, but the game nonetheless did not like that.

**Comment by gameboy9** [comment]
Ahhhh... I think I know what's going on.  The Thief's Key, earned in Chapter 2, gets reassigned to the hero for some reason when the heroes are randomized.  That probably needs to be redirected to the Chapter 5 hero in that case...

**Comment by hyrule1989** [comment]
I've started another attempt, with item shop and treasure randomization.  I'll let these pictures explain what the problem is.
![dw4rh_965368334_001](https://cloud.githubusercontent.com/assets/19522923/15636211/cb9110ba-25c5-11e6-938d-728501388bfb.png)  
![dw4rh_965368334_002](https://cloud.githubusercontent.com/assets/19522923/15636213/d393750a-25c5-11e6-9362-a80bd8babbbd.png)

**Comment by hyrule1989** [comment]
Also, with randomized monster zones and randomized bosses enabled, the Chapter 5 Keeleon fight did not give me Keeleon.  
![dw4rh_965368334_003](https://cloud.githubusercontent.com/assets/19522923/15638337/3f126030-25ed-11e6-9bba-638aa9d4d9f2.png)

**Comment by gameboy9** [comment]
May I have seed numbers as well as what specifically was checked for these issues, please?  Also, one more request... when you run into a new bug, can you create a new issue, please?  It keeps things organized.  Thanks!  :)

**Comment by gameboy9** [comment]
The item store has been fixed in version 0.6.5.

**Comment by hyrule1989** [comment]
Seed for the shop and keeleon battles was 965368334.  Randomized heroes from chapter 1-4 as well as randomized acquisition in chapter 5. Randomized monster zones, treasures, and stores only, with sped up battles.

And I didn't know if it was better organized with seperate issues or the same.  I'll make new ones from here on out.

**Comment by gameboy9** [comment]
OK, I think I have everything taken care of with this issue.  If I'm correct about that, please close this issue... and if not, please advise.  Thanks for your help!  :)
