### ISSUE TITLE
Various...

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#11]
Metal enemies really should retain their defense.. even on ludicrous
Metal enemies should still run.
Metal enemies should not be absolutely easy to kill with spells.
Small medals shouldn't be in 1-4 if they can't be sold.  For that matter items not required in ch1 shouldn't be in 1, same with 2, 3 and 4.
If you get the birdsong nectar, whatever is in the birdsong nectar spot becomes unfindable!
NPCs should be randomized as much as you can and compliment the heroes that they accompany in each chapter ( ignoring 5 ).  Healie could be a tank if the hero of the chapter is say, a wizard.  Healie could be a wizard if the Hero of the chapter is Cristo or Nara, and so on.
You can sell the same item an infinite number of times in the shop in ?Bonmalamo? in chapter 3.
In my case, I found a mirror shield and easily reached 999999999999999999999999999999999999999999999999999999999999999 gold.
The character who is the 'hero' of chapter 5 may be gimped and not properly randomized, I could be wrong.
Middle pot in woodsman hut was still empty for some ??? reason.
If you get the Symbol of Faith before entering the Symbol of Faith cave, you can cause all sorts of glitchy hijinks and fun stuff!!
Particularly if you bring Hector with you!  Buwahahaha.
Game was not designed for 4 characters in that cave.....
You can also permenantly lose a character.  If that character is the Hero ( as in my case ) Ragnar would never join you.  Ever.  Period.  Softlocking the game.  The class 'Hero' does not matter in this case.
Poison Needle somehow was not ???equippable by anyone???
Dangerous and potent unique items should either not be sellable or be sold for tons of dosh.  Case in point, Metabble sword.
You can abuse buying seeds.
I can buy as many mirror shields as I want from the casino because its soooo cheap in the casino.  These shields sell for 9000.
The shop behind the magic door in Santeem should Not be kept to the same script as the others.
Esturk didn't change much.  Died far too easily.
You can run from random encounter bosses.  For good reason.
If Zenithian equipment is in the cascade cave, the stones of drought should NOT BE INSIDE the Zenithian Tower or later.

Seed 1341167485
All character names the same except:
Healie is SlmHeals
Laurent is Laurence
Strom is Richard
Orin is Oghram
Lucia is Celes
Doran is Drago
1-4 heroes shuffled
5 shuffled
No other chapter settings
adjustments
Zones
Stats/Attacks LUDICROUS
Resistances as Per Above
Treasures
Stores
Who can Equips
Hero Stats LUDICROUS
Sped up battles
150% exp
150% gold
Encounter rate was left blank.
I thought I set the checks next to these but on reopening they weren't checked.

Unsure if Birdsong Nectar is unfindable by Zombehtraine as he did get to chapter 3.

Metal Slimes like to cast Sacrifice 
Metal kings LIKE TO GET SERIOUS

**Comment by gameboy9** [comment]
The only thing that's a duplicate is the small medals thing.  (Issue #8)  Everything else I will take a look at, but it will take a while.  Thanks again for testing this almost all the way through!  :)

**Comment by Shoobers** [comment]
The pots in haville were empty as well.  The ones in the jail.

**Comment by Shoobers** [comment]
Add "Put in option to allow us to use tactics."  Whether in game or in the randomizer, I don't care.

**Comment by gameboy9** [comment]
Items remaining:
- Relook at Haville's jars using Shoob's seed
- Adjust pricing so seeds can be sold at stores. (found part of the pricing model so far)
- Adjust pricing for casino items (need to look at actual item prices first)
- Adjust pricing for small medal items (need to look at actual item prices first)
- Force small medals to be sold
- Randomize NPC acquisition

**Comment by gameboy9** [comment]
I'm ruling this to be fixed.  If there's still an issue in Haville, please reopen this issue, or create a new issue.  Thanks!
