### ISSUE TITLE
Mini Medal Guy Sells Everything For 20 Mini Medals

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#12]
Similar situation to the Casino, seems to sell everything for the max amount of medals possible.

**Comment by Shoobers** [comment]
Not everything.  The king will sell its original items for the right price ( hat of happiness for 4, for example. )

**Comment by gameboy9** [comment]
Think I need to do the same thing I did in the casino...

**Comment by gameboy9** [comment]
The bug was addressed in 0.6.12 - the items are now 1-4-6-20 medals.  Still need to address changing the prices though...

**Comment by gameboy9** [comment]
I'm pretty sure this is good to go as well.
