### ISSUE TITLE
0.7.0 Things to do

### ISSUE THREAD

**Issue by gameboy9** [gameboy9/DW4RandoHacker#13]
- Flags!!!!!
- Chapter 1-4 Bosses probably shouldn't have crit hit, nor should they be allowed to call for "boss help".
- Set prices for Casino (20 GP / coin)
- Set prices for small medal (4000 GP / medal)
- Allow medals to be sold (1000 GP / medal)
- One sage's stone all game (remove from common treasures list)
- Allow other items to be sold if possible.
- Randomize NPC acquisition
- Separate monster abilities and monster stats.
- Recalculate stat growth.  Use bases from 1-5, and multipliers from 8-40, across all stats.
- Combine "C1-4 Hero Acquisition" and "C5 Hero Acquisition" checkboxes.
- Combine all the randomization levels, for simplicity.
- Add gold as possibilities for random treasures.  Make common items... more common!
- Did I mention flags?!

This should resolve issue #4, #6, #7, #8, #11, and #12.

**Comment by Zombietraine** [comment]
I'm excited! 👍

**Comment by gameboy9** [comment]
Randomize NPC acquisition is going to be REALLY REALLY tough!  The first four chapters are fine, it's the fifth chapter that's going to screw me!  :(

**Comment by Shoobers** [comment]
Somehow I did not actually get Ragnar after killing Keeleon... only had 7 chosen to beat the game.

**Comment by gameboy9** [comment]
0.7.1 Issues:
- Some weapons and armor are multiplied wrong. (Copper sword, Silk Robe, Iron Apron)
- Add flags to the ROM filename.

**Comment by gameboy9** [comment]
This is completed, barring bugs, which new issues should be created for.
