### ISSUE TITLE
Chapter 4 Unbeatable If You Do Not Get Orin

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#15]
With randomized NPCs, you have a chance of not getting Orin in Chapter 4 resulting in being unable to open Keeleon Castle. Seed is 441159319, was not getting anything in the Flags field so my randomized settings are below...

Seed: 441159319 | Randomized (Light) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats. Adjustments: Exp 150%, Gold 150%, Chapter 3 Shop and Tunnel Cost 1G, Battle Speed Increased, Control of Chapter 5 Heroes.

**Comment by Zombietraine** [comment]
Thinking this might be an issue in Solo Character Challenge as well. It looks like you get a copy of your character when you pick up NPCs (at least I got a second Brey in Chapter 1 when getting Healie). If you would get a second Brey in Chapter 4, that'd eliminate the possibility of getting to Keeleon.

**Comment by gameboy9** [comment]
That's possible, and definitely in the realm of possibility.  I tried to prevent this by changing the required character from #$89 (all NPCs have that hex value) to #$8x, where X is the solo hero.  Therefore, it's possible that solo hero is still OK.  What I'm thinking is that it passes the #$89 check, but there's a further check to make sure it's Orin.  ($6114 = #$C6, not #$C5, which is Healie)  I'll find out for sure this evening.

**Comment by gameboy9** [comment]
OK, this one is all fixed up.  I was right, it was a direct LDA...
