### ISSUE TITLE
Randomizer Program Crashes When Clicking From Flag Box to Seed

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#16]
Below are the error details...

----

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DW4RandoHacker.Form1.determineChecks(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnLeave(EventArgs e)
   at System.Windows.Forms.Control.NotifyLeave()
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DW4RandoHacker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mike/Desktop/Dw4%20Randomizer/DW4RandoHacker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------

**Comment by Zombietraine** [comment]
Also, after creating a new "hack" I'm not seeing anything go into the Flags field. Should there be something there?

![settings](https://cloud.githubusercontent.com/assets/20928976/17670671/261eb9e4-62e1-11e6-8bd9-4892df43d961.png)

**Comment by gameboy9** [comment]
Yeah, something should wind up there every time you change a combo box or a check box.  I think I might have a couple odd things going on.  0.7.1 will have the flags in the ROM name though.

**Comment by gameboy9** [comment]
Having heard nothing about this bug over the last couple of versions, I am considering this one resolved.
