### ISSUE TITLE
Question: Panon and Chapter 5

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#19]
I was wondering if you do not get Panon before you go to Stancia, would you still be able to talk to the King to get whatever item he is giving? I'm playing through now and just got Panon as scheduled, but wasn't sure if that was hard coded or not. Only time it would be an issue is if the King had a key story item I suppose...but figured I'd ask if was taken into consideration yet or not.

**Comment by Zombietraine** [comment]
I actually just finished the conversation with the king and got a second Zenithian Helm. I don't recall where I found the first one. So helm is hard coded to the king, therefore not getting Panon could be an issue?

**Comment by gameboy9** [comment]
OK, that's weird... but anyway, it should be checking who is acting as Panon, then passing through to get the Helm.

**Comment by Zombietraine** [comment]
Awesome! I'm going to finish this run tonight so I'll let you know the results if there is anything noteworthy.

**Comment by gameboy9** [comment]
This is now listed as a bug in issue #23, so I'm going to close this one.
