### ISSUE TITLE
Brey joining in Ch5.

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#21]
For some reason I've had brey, and I think its specific TO brey, join multiple times when someone else is meant to.  Ludicrous and randomized chapter 5 joining/chapter 1-4 spawning.

**Comment by gameboy9** [comment]
May I have a seed number(especially) and flags, please?  Thanks.

**Comment by gameboy9** [comment]
From Shoobs:

 211363249 Random hero acquisition, award for chapter 2 tournaments everything else checked but control all characters and at ludicrous.

**Comment by gameboy9** [comment]
OK, I'm sure I squished this bug, so I'm closing this issue.
