### ISSUE TITLE
2 Necrosaros

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#22]
Looked like I got 2 Necrosaros and, once I finished the first phase on one of them, he went through all his phases in one hit until the final phase. Highlight is below.

https://www.twitch.tv/zombietraine/v/85002764

Seed Info Below...
Seed: 1474378798 

Randomized (Light) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, NPCs, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats, Who Can Equip. 

Adjustments: Exp 150%, Gold 150%, Chapter 3 Shop and Tunnel Cost 1G, Battle Speed Increased, Control of Chapter 5 Heroes.  **

**Comment by gameboy9** [comment]
While funny, that boss fight should not be adjusted.  It should be just Necrosaro.

**Comment by gameboy9** [comment]
I think that I took care of this in 0.9.0.
