### ISSUE TITLE
Strom Cannot Get Helm From King

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#23]
Strom gets the dialogue that he is not funny...poor Strom :(

https://www.twitch.tv/zombietraine/v/85003611

I did get Panon later, where I would have picked up Lucia in the tree. If Panon is available in the Chapter, does it just force you to get Panon and only work with any NPC if he is not available?

Seed Info Below...
Seed: 1474378798

Randomized (Light) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, NPCs, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats, Who Can Equip.

Adjustments: Exp 150%, Gold 150%, Chapter 3 Shop and Tunnel Cost 1G, Battle Speed Increased, Control of Chapter 5 Heroes.

**Comment by gameboy9** [comment]
No, if Strom is acting as Panon, Strom should be funny.  I'll take a look.

**Comment by gameboy9** [comment]
I think this is fixed now.
