### ISSUE TITLE
Bugs found.

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#25]
Female Hero upon learning Outside or Revive did not gain them as Field Spells.  I think some spells may not be properly displayed on levels as I have gotten spells without actually being shown I learned it.  Not 100% sure on this however.

Sampson on ludicrous can get Unhittable Defense, as can Hun.

Doran acting as Laurent does not leave the party.

Mimics in chapters 1-4 shouldn't occur, though maneaters can.  May also want to bound the difficulty of monsters with Both.  Even on Ludicrous.

Mirror of Ra is thankfully throwawayable.

You should be asked if you want to throwaway a good item like the Sword of Miracles during a "You have too full of an inventory" after battle sequence ( treasure chest ).

**Comment by gameboy9** [comment]
I think this duplicates issue #26, is that right?

**Comment by Shoobers** [comment]
Yep!

**Comment by gameboy9** [comment]
OK, closing this, keeping issue #26 open.
