### ISSUE TITLE
Bugs found.

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#26]
Female Hero upon learning Outside or Revive did not gain them as Field Spells.  I think some spells may not be properly displayed on levels as I have gotten spells without actually being shown I learned it.  Not 100% sure on this however.

Sampson on ludicrous can get Unhittable Defense, as can Hun.

Doran acting as Laurent does not leave the party.
Different seed
Orin acting as Laurent does not leave.
Doran acting as Strom does not leave.
if the CHOSEN is not in the FIRST slot when the NPCs are meant to leave, slot 2 and 3 will leave.
This will cause not-taloon to leave and soft lock the game, as below.
As a result of this, I've found out the auxillary characters in the lead will make treasure chests so common that you can't move five feet without getting a broad sword or half plate.

Mimics in chapters 1-4 shouldn't occur, though maneaters can.  May also want to bound the difficulty of monsters with Both.  Even on Ludicrous.

Mirror of Ra is thankfully throwawayable.

You should be asked if you want to throwaway a good item like the Sword of Miracles during a "You have too full of an inventory" after battle sequence ( treasure chest ).

Healusall softlocks the game.

Found both the Padequia seed and the Root.
Obviously should not happen....and I think this can break the game.

I've also verified.  Brey joining you in mintos is bugged.

Somehow Cristo left the party in chapter 3, leaving Doran behind and the game is softlocked.

Sadly you need to buy a shop before leaving the chapter :(

Added:
The AI does not know how to use their new spells.
Chance is added to field commands.  Clearly does not work as intended.

**Comment by Shoobers** [comment]
Found the Padequia seed AND root.

**Comment by Zombietraine** [comment]
I have a bit of feedback on what you're seeing Shoob, figured I'd add it here...

1. I've only been messaging with spell randomization for a bit but I have not seen an issue with field spells not appearing on the field menu. This is assuming you're using spell randomization with 0.8.0. I'll keep an eye out for this in upcoming playthroughs.

2. Re: Sampson, I'm of the mindset that if you're playing on Ludicrous then this type of thing should be expected. If this is happening on Light I could see an argument against that. Ludicrous should be exactly that, Ludicrous. 

3. Re: Mimics, I feel the same as I do with Sampson, if you're playing on Ludicrous, I'd expect the worst of the worst in Chapters 1-4.

4. How does Healusall softlock? I haven't experienced that yet. 

5. Re: Cristo lol thats hilarious. Doran, could never run a shop with those short arms!

**Comment by Shoobers** [comment]
1.  It happens to the hero only, male or female.  There's multiple spells this happens to.

2.  If you're using Alena/Ragnar/Taloon with <40 hp and a low str build...I suppose you can hope for crits if she has defense...but what if she has low agi, low str, low hp, and refuses to wear anything other than a leather dress and no hats?

3.  Its an assured death in most cases.

4.  If used in the field in chapters 1-4, it will softlock.  It could also have something to do with the fact I used it after beating chapter 2 on someone.

5.  Yeeeeeeeeeah this one is a dousy.

**Comment by gameboy9** [comment]
Does HealUs softlock as well?  Now that I'm thinking about it, HealUsAll is NOT awarded as a field spell in the vanilla ROM...

Regarding Chapter 3, there's probably some direct LDAs I have to address to figure that problem out.  I typically don't bother with that chapter as far as NPCs are concerned...

**Comment by Shoobers** [comment]
Healus does not softlock.

**Comment by Shoobers** [comment]
Hector acting as Panon does not trigger Zenithian Helm ( though I still had Strom acting as Hector and lacked Alena, Cristo and Ragnar's replacements at the time ).

**Comment by gameboy9** [comment]
This is coupled with issue #38, which I have resolved.  Therefore, I'm considering this issue completed.
