### ISSUE TITLE
Suggestion: Ludicrous enemies should always have infinite MP

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#29]
I find way too many enemies in chapters 1-4 that try to cast spells they can't afford, because in the base game they have no MP.  I don't know how to handle that at lower randomization levels, but I think any enemy that has spells/skills on Ludicrous should have infinite MP so that they can always cast their spells.

**Comment by Shoobers** [comment]
I wouldn't go with infinite, but adding a random mp amount would be nice

**Comment by gameboy9** [comment]
I go back and forth with this, especially after applying a similar algorithm of Ludicrous randomization in DW2 Randomizer, where all the monsters do have infinite MP.  More often than not, it resulted in many of the monsters party wiping, so I had to restrict abilities of low level monsters.

And that's why I'm tepid in giving all monsters some form of MP.  I was thinking 50% chance of no MP, 50% chance of up to 16 MP personally.

**Comment by Zombietraine** [comment]
> And that's why I'm tepid in giving all monsters some form of MP. I was thinking that if a monster has no MP, it gets a 50% chance of no MP, and a 50% chance of up to 16 MP personally.

I like that idea better than infinite.

**Comment by Shoobers** [comment]
Or something that gives them a relative amount of mp based on the spell

**Comment by TheCowness** [comment]
Basing it on the cost of the spell would take work, which is why I figured it would be easiest to just give them 255 (infinite) MP.  I just think it gets a little old when most of the early-game enemies are "Demonites" who can't cast their spells.  It makes them weaker than if they didn't have spells at all, since they'll waste turns trying to cast.  In my last playthrough of chapters 1-4 I only ran into about half a dozen enemies with troublesome skills (Necrosaro fire/ice breath, or ridiculous critical hits).

**Comment by gameboy9** [comment]
I think what I'm going to do is if a monster has <= 16 MP, they get a 50/50 chance to have that changed.  (So if a monster has 4 MP and lose the 50/50, it will still have 4 MP)  If a monster wins the 50/50, their MP will change to a value from 0-32.

**Comment by Shoobers** [comment]
I'm good with this.

**Comment by gameboy9** [comment]
This one is implemented as mentioned previously.
