### ISSUE TITLE
Revival/Detoxicate/Lullaby Jingle Not Sped Up Properly

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#31]
Just gonna leave a highlight for this one:
https://www.twitch.tv/thecowness/v/86279412

**Comment by gameboy9** [comment]
Actually, that's because I didn't get the opportunity to speed it up yet.  But that will be in the next version.

**Comment by gameboy9** [comment]
OK now that I saw the clip, I'm thinking there's also a bug laying around here...

**Comment by gameboy9** [comment]
Ohhhhh... I wasn't expecting that to happen with Taloon's special.  Guess I'll have to be Taloon for a while then...

**Comment by TheCowness** [comment]
It also happens when you talk to the priest and revive or detoxicate.

**Comment by gameboy9** [comment]
Ohhhhhhhhhhhhhhhhhh... That means I probably "missed", meaning I wrote the wrong ROM address.  This should be a much easier fix than I anticipated then.

**Comment by gameboy9** [comment]
I think this one is solved.
