### ISSUE TITLE
Birdsong Nectar Not Found in Chapter 2 in 0.9.2

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#32]
Hoping I'm wrong on this, but I wasn't able to find the Birdsong Nectar in Chapter 2 in the following seed. I've added a highlight that shows me going back and looking in all of the places I know of for items in Chapter 2.

https://www.twitch.tv/zombietraine/v/86840085

Version: 0.9.2
Seed: 1579775446

Randomized (Light) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, NPCs, Spells, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats.  

Adjustments: Exp 150%, Gold 150%, Chapter 3 Shop and Tunnel Cost 1G, Battle Speed Increased, Control of Chapter 5 Heroes, Wait Music Speed Increased.

**Comment by gameboy9** [comment]
Upon successful completion of your run on 9/1, I am closing this issue.
