### ISSUE TITLE
Iron Safe

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#34]
Once more found in Chapter 2, birdsong tower.  DSF found it.  Two birdsong nectars also found in ch2.
Endor sale lists are completely empty and you have to select items to see what they are.  The weapon shop had a major out of bounds error.

**Comment by gameboy9** [comment]
Trying to get seeds and flags with DSF... but haven't been successful in duplicating the issue yet.

**Comment by gameboy9** [comment]
Since this issue has not been duplicated, I am going to close this issue.  We can reopen this issue if the bug pops back up again.
