### ISSUE TITLE
Taloon (Chapter 5 Hero) Removed After Z Helm Aquisition

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#38]
Used Healie as Panon to get the Z Helm, upon exiting town, Healie stayed, Taloon (who was the Hero in Chapter 5) was gone. This prevented me from getting to the Balzack fight in Santeem which likely held the Z Sword as I exhausted all other chests I could think of lol. Highlight is below along with Seed info...

https://www.twitch.tv/zombietraine/v/94347612

Seed: 380447697 
Randomized (Silly) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, NPCs, Spells, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats.  

Adjustments: Exp 150%, Gold 150%, Battle Speed Increased, Wait Music Speed Increased.

**Comment by gameboy9** [comment]
I think there's a direct LDA that needs changing, but I missed.  I'm hoping that this will be an easy fix.

**Comment by gameboy9** [comment]
I was correct, a direct LDA needed changing that I didn't see earlier.  It's all fixed up.  :)
