### ISSUE TITLE
Incorporate ocean encounter bug fix

### ISSUE THREAD

**Issue by awjackson** [gameboy9/DW4RandoHacker#41]
As you know, unlike DW2 and DW3 where the ocean is divided into weaker and stronger encounter zones just like the land, in DW4 you encounter exactly the same (weak) ocean monsters no matter where you go. There are higher-level ocean monsters in the ROM, but most of them can't be encountered (a few of them do appear in dungeons).

This turns out to actually be the result of a program bug which can be trivially fixed, as documented here: https://tcrf.net/Dragon_Warrior_IV_%28NES%29 It would be interesting to have this bug fix as an option in the randomizer.

**Comment by gameboy9** [comment]
This was implemented as prescribed and included in the 0.11.1 release.
