### ISSUE TITLE
Inescapable Gigademon Fight

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#42]
I was doing a randomizer tonight with all flags on except for randomized monster resistances, and when I got to the final boss rush, I was able to re-fight the minibosses (Confirmed all but Infernus Shadow) by talking to their corpses.  Not a big deal, except that Gigademon wouldn't let me leave -- the "surprise attack" triggers again when you try to walk away from him after beating him.  I had to die to him to get away.  The barrier broke as normal after beating all four bosses, though sadly I could not break the barrier just by beating Gigademon four times.

The only real issue here is that Gigademon wouldn't let me leave after killing him.  My guess is this behavior was caused by the "No Field Text" flag, but I have no rational basis for this guess.

**Comment by gameboy9** [comment]
Hmmmm... since "no field text" has been replaced with "speedy text", I'm going to close this issue.  Please reopen if this issue resurfaces.
