### ISSUE TITLE
Spell randomization bug

### ISSUE THREAD

**Issue by Reiska42** [gameboy9/DW4RandoHacker#46]
So I ran into an interesting bug on my run today: Nara keeps "learning" Revive every time she levels up, but it isn't added to her spell list.

Randomization info:

Seed = 1909074054
Options = Randomize hero acquisition, NPC scaling, 200% EXP, 200% gold, 3/4 encounter rate, speed up battles/wait music, randomize monster zones/monster stats/monster attacks/monster resistances/treasures/stores/hero stats/hero spells, random level Light.
Other: All PC names are changed to the DQ4 DS translation names as follows:

Ragnar = Unchanged
Healie = Unchanged
Alena = Unchanged
Cristo = Kiryl
Brey = Borya
Taloon = Torneko
Laurent = Laurel
Strom = Hardie
Mara = Maya
Nara = Meena
Orin = Oojam
Hector = Hoffman
Panon = Tom
Lucia = Orifiela
Doran = Sparkie

As a note, the labels on the name fields in the randomizer are flipped for Laurent/Strom and Mara/Nara, as well.

**Comment by Reiska42** [comment]
Addendum: At level 8, she "learned" Healus.  Likewise, this didn't show up on her spell list.

**Comment by Shoobers** [comment]
Seconded: Most healing spells that I've recieved - Healmore, Healall, Healus, Healusall, Revive, do not get saved as field spells and are constnantly relearned.  I haven't seen Heal or what happens with Outside / Return / Day - Night / and other similar spells but I have a feeling its related to field spells specifically.

**Comment by Reiska42** [comment]
Yeah, I've noticed it's always field spells that are doing this.  I'm not getting them saved as battle OR field spells though.

**Comment by Shoobers** [comment]
Were you using a female Hero?

**Comment by Shoobers** [comment]
Nevermind, I see you used 'her'.

**Comment by Reiska42** [comment]
The "her" was actually referring to Nara, but that said, yes, female hero.

**Comment by gameboy9** [comment]
This should be resolved. Please let me know if I'm missing anything; if not, please close. Thanks!

**Comment by Reiska42** [comment]
I was able to learn a field spell on the new version, so it appears to be fixed.
