### ISSUE TITLE
Items starting at incorrect point

### ISSUE THREAD

**Issue by gameboy9** [gameboy9/DW4RandoHacker#47]
Like the fire claw, for example, point at the allies first, not the enemies.  I bet it's because I changed all of the prices of the items, and that's having a say...

**Comment by Shoobers** [comment]
This is very much an annoyance.  Magma staff also targets the party while Sacrifice cast by enemy targets enemy party.

**Comment by gameboy9** [comment]
Pretty sure this is taken care of, so I'm going to close this one.
