### ISSUE TITLE
Chapter 5 character joining bug

### ISSUE THREAD

**Issue by Reiska42** [gameboy9/DW4RandoHacker#49]
Another run, another bug! 

Seed: 259211608
My settings are the same as the run in the last report except that randomize who can equip is now ON and randomize spell lists is OFF, and double walking speed is ON.

Everything went smoothly (well, as smoothly as a randomizer run can go) until chapter 5.  However, after finishing the Padequia cave and picking up "Alena and Cristo", only one character was added to my party (Taloon).  Also, the hero was mysteriously removed from my active party, although remains in my roster.  I suspect that it tried to add her again when she was already there based on that.

Fair warning if you go to test this one: I suggest cheating on chapter 1 and early chapter 5.  Chapter 1 you get to deal with a Taloon/Panon pair which makes the chapter's boss an absolute nightmare, and early chapter 5 you have Nara who can't gain HP to save her life (I had to grind to level 12 to get past the betrayal cave).

Incidentally: this seed also has a pretty much unbeatable Keeleon fight (there's 3 copies of him in the fight and they can drop 700 damage crits).

**Comment by gameboy9** [comment]
I need a slight clarification; did "Brey" join you first, then "Alena/Cristo", or did you have "Alena/Brey/Cristo" join you all at once?

**Comment by gameboy9** [comment]
This is all fixed up for sure, so I'm closing this issue.
