### ISSUE TITLE
Insane critical hits?

### ISSUE THREAD

**Issue by Reiska42** [gameboy9/DW4RandoHacker#50]
I'm not sure if this is actually a bug or not, but I keep running into the odd monster here and there that does extremely disproportionately high damage with (frequent) critical hits which always do a fixed amount of damage.  For instance, the seed I reported the chapter 5 party bug on the other day, Keeleon would randomly crit for 700 damage.

Is this some cutscene attack or something that's getting randomized into enemy AIs? ;)

**Comment by gameboy9** [comment]
I think it's just a random thing in the AI scripts where 700 damage can occur.  If you look at my cover page on my Twitch or Twitter pages, I gave a slime 1,023 strength and forced a "super critical hit", and it dealt 5,115 damage points.  Talk about ouch...

**Comment by gameboy9** [comment]
Now the question is should bosses have that ability... hmmmmm...

**Comment by Reiska42** [comment]
I've seen it on regular trash enemies too for what it's worth.  For example, my current run (seed 739176551, random hero acquisition/NPC scaling on, tournament EXP on, 25000GP shop/1GP tunnel, C5 control all characters on, 300% EXP, 200% gold, 1/2 encounter, speed up battles and wait music on, all options on randomization tab toggled (light randomization), it showed up on Orcs in the C1 tower (150 damage there).  

My gut feeling is that it probably should be limited to the late-game bosses on light randomization (maybe Esturk and later), and more unrestricted as you turn up the randomization level.  Still, it IS funny when it shows up on something dumb like slimes :)

**Comment by gameboy9** [comment]
Changed a while back... but I don't believe that early bosses (Chapter 1-early 5) have critical hits anymore.  I may change this to be optional for those who are crazy though...
