### ISSUE TITLE
Code Break When Fighting Imposters Accompanying Keeleon

### ISSUE THREAD

**Issue by WillWagnerMusic** [gameboy9/DW4RandoHacker#58]
If necessary, I can send the save state, rom, and settings screenshots

In Chapter 4, just before the fight with Keeleon:
![dragon warrior 4 randomizer code break 1](https://user-images.githubusercontent.com/29822602/27764897-a2f17a28-5e72-11e7-9b6c-bca2d4cae2dc.jpg)

Start of the fight:
![dragon warrior 4 randomizer code break 2](https://user-images.githubusercontent.com/29822602/27764898-a2f90aae-5e72-11e7-95a5-90fb7f2e5958.jpg)

Imposter casts "Transform":
![dragon warrior 4 randomizer code break 3](https://user-images.githubusercontent.com/29822602/27764900-a2fccf04-5e72-11e7-94e9-241d77df7509.jpg)

End of Fight:
![dragon warrior 4 randomizer code break 4](https://user-images.githubusercontent.com/29822602/27764899-a2f9cfe8-5e72-11e7-8697-901df243a200.jpg)

Game errors continue after fight:
![dragon warrior 4 randomizer code break 5](https://user-images.githubusercontent.com/29822602/27764929-17a63778-5e73-11e7-99ea-317f25130f6a.jpg)

(First post, so I'm still learning how to format these with the proper information, advice is always appreciated!)

One more thing: I think the Mara/Nara naming component, or possibly their equipment assignments may be inverted.

**Comment by gameboy9** [comment]
OMG... that's nuts!

So Imposters shouldn't exist in any formation in RandoHacker, and you basically showed why.  They have a special Transform ability that screws up the graphics from other monsters, which is why you only see them with no other monster type in the vanilla game.  I will remove the Imposters from a possible boss group.

**Comment by gameboy9** [comment]
OK, this one should be all patched up.  Thanks again for letting me know!

**Comment by WillWagnerMusic** [comment]
I'm just glad I can help! Thanks for all your work! I love the DW games,
and appreciate all your efforts to make them even more fun!
