### ISSUE TITLE
All Casino Store Items Cost 18570

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#6]
Seen this in multiple seeds, but in this particular instance, seed and settings were as follows...

Seed - 1990197176

Options:

Random Chapter 1-4 Heroes
Random Chapter 5 Hero Acquisition
Random Monster Zones
Random Monster Stats - Light
Random Treasures
Random Stores
Random Hero Stats - Light
Random XP Gain
Random Gold Gain
Speed Up Battles

Saw this in Chapter 2, I'll check other Chapters as I go.

![casinocost](https://cloud.githubusercontent.com/assets/20928976/17526179/2e102342-5e34-11e6-9a35-226d6e96d16c.png)

**Comment by gameboy9** [comment]
Need to figure out where the casino costs are to begin with... so this will have to be in the next minor version most likely.

**Comment by gameboy9** [comment]
Never mind... I just figured it out, and fixed the issue.  New release forthcoming.  Leaving the issue here though because I want to calculate a reasonable price for the items...

**Comment by gameboy9** [comment]
This one is taken care of.
