### ISSUE TITLE
Not seeing an .exe file after download?

### ISSUE THREAD

**Issue by dandacheerman** [gameboy9/DW4RandoHacker#62]
Would love to play this game but after download and unzip, I am not seeing an .exe file to open the menu to hack the rom. 
![1](https://user-images.githubusercontent.com/34035312/33276424-8ad4676e-d363-11e7-9c37-6018185ab265.png)
![2](https://user-images.githubusercontent.com/34035312/33276474-aaac849a-d363-11e7-89e1-0ba33c7a4767.png)
![3](https://user-images.githubusercontent.com/34035312/33276507-bf34b504-d363-11e7-8ca1-3cd65f53d44a.png)

**Comment by gameboy9** [comment]
Ahhhh... I think you downloaded the code, but not the EXE.  You can do this by looking at the releases page here:  https://github.com/gameboy9/DW4RandoHacker/releases/tag/0.13.1

Hope this helps out!

**Comment by dandacheerman** [comment]
That did the trick! Thank you so much!
