### ISSUE TITLE
No .exe file to run program.

### ISSUE THREAD

**Issue by emunden1** [gameboy9/DW4RandoHacker#63]
I can not for the life of me figure out how to get this program to run. There is no instructions or anything regarding problems. I would really like to use this program now that I have been running various randomizers.

**Comment by TheCowness** [comment]
The exe isn't in the code base; you have to download it separately from the Releases tab, over here: https://github.com/gameboy9/DW4RandoHacker/releases/tag/0.13.1

Github does a pretty good job of hiding that tab.
