### ISSUE TITLE
Mara Learns Firebane instead of Return without Randomized Spells

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#67]
https://clips.twitch.tv/AgitatedRudeSnailWOOP

On version 0.13.1 of the randomizer, but I don't see anything related to this in the patch notes.  Flags were t2111bS200 seed was 1723006585 (same for the other issue I submitted tonight).  When Mara hit level 8, she had Firebane added to her battle list and Return added to her field list, and I did NOT have spells randomized.

Helped me beat the Lighthouse Bengal, though.

**Comment by gameboy9** [comment]
This is currently by design.  If Mara is the Chapter 1 or the tournament hero and spells are not randomized, she will learn Firebane at level 8 and Blazemore at level 12.

Additionally, if Brey is the Chapter 1 or the tournament hero and spells aren't randomized, Snowstorm is learned at level 8.
