### ISSUE TITLE
Water enemies at the start of chapter 5 with only randomized map

### ISSUE THREAD

**Issue by xJackieBx** [gameboy9/DW4RandoHacker#68]
Was trying out the new map randomizer and wanted to do the game "normal" with all randomizations turned off (treasures, stores, etc.) and just try the new map, chapter 5 is only spawning water enemies making the beginning of it extremely tough.  I assume this wouldn't be an issue if things like monster zones were randomized though. 

Chapters 1-4 were 99% normal aside from maybe 1 or 2 water battles that happened to spawn then as well.

**Comment by gameboy9** [comment]
I believe I fixed that with version 2.0.2.  Give it a go and see if that helps matters.  Please reopen if there's still an issue with seed and flags.
