### ISSUE TITLE
Returning to Tempe in Chapter 2 is bugged

### ISSUE THREAD

**Issue by xJackieBx** [gameboy9/DW4RandoHacker#69]
I'm assuming since you can't return there in chapter 5 that it's just an oversight, but returning there in chapter 2 will instead return you to (I'm guessing) the default location of where the town should be.  Had 1 seed that had me end up in the middle of the ocean and another that put me on an island with Konenber/Aneuex and what not, while in chapter 2

**Comment by Polantaris** [comment]
There's a few examples of this. The water cave (where one of the Zenithian pieces is in vanilla, north of the Small Medal King) will warp you to its original location if you cast Outside in it (possibly leave it normally too but I cast Outside).

I also went to the location marked on the Treasure Map and it teleported me to Keeleon Castle after a huge delay, it felt like the game didn't know what to do and just sent me to a backup location when it failed.

**Comment by gameboy9** [comment]
Should be resolved in the next release!

**Comment by gameboy9** [comment]
Still have to address Shrine of Breaking Waves... I'll deal with that in a near future release.

**Comment by gameboy9** [comment]
Now I took care of the Breaking Waves cave; it should be in the next release.
