### ISSUE TITLE
Chapter 4 teleport bug

### ISSUE THREAD

**Issue by Tundra83** [gameboy9/DW4RandoHacker#70]
Made a youtube video showing what it is doing instead of trying to explain it. https://www.youtube.com/watch?v=KdJHdfJkTEk&feature=youtu.be

**Comment by Dwedit** [comment]
Just to be sure, you aren't using the debug mode game genie code?  It changes the first return destination to Keeleon.

**Comment by Tundra83** [comment]
I was using no codes or anything. Just the randomly generated game file.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Dwedit** [comment]
Just saw it happen here:

https://clips.twitch.tv/SquareFineGaurKlappa

**Comment by Polantaris** [comment]
I think this is related to what I mention in this post here:

https://github.com/gameboy9/DW4RandoHacker/issues/69#issuecomment-498049326

If that's the spot where the Treasure Map is marked it seems to warp you to Keeleon after a large delay (potentially as a fallback result).

Honestly I don't even remember what's supposed to be there in the main game.

**Comment by xJackieBx** [comment]
the mark on the map is where the world tree (zenithian sword) is located in vanilla

**Comment by gameboy9** [comment]
Should be resolved in the next release!
