### ISSUE TITLE
Boat spawned in a small pond after getting it in Mintos

### ISSUE THREAD

**Issue by xJackieBx** [gameboy9/DW4RandoHacker#72]
After beating the lighthouse and getting my boat, instead of putting me in the ocean it put me in a small pond that was also right next to the town, as shown here..

https://twitter.com/JackBartlett89/status/1135801040547303424

Seed - 15627772497
flags - ms30xVyEuB

**Comment by gameboy9** [comment]
I think that this is because I was mapping lake "islands" before merging islands, not after.  I think that I fixed this and it will be released in the next version.
