### ISSUE TITLE
using wing to branca sent me into the middle of the mountains on small map size

### ISSUE THREAD

**Issue by xJackieBx** [gameboy9/DW4RandoHacker#73]
using a wing of the wyvern to go to branca (to buy more wings) sent me to the wrong location, in this case it was in the middle of the mountains that surround the small map variant. didn't have any more wings nor the return spell to remedy it.  

same seed as my other issue

Seed - 15627772497
flags - ms30xVyEuB

**Comment by gameboy9** [comment]
Think that I fixed it.  It will go into the next release.
