### ISSUE TITLE
Chapter 3 Lakanaba Return Point incorrect

### ISSUE THREAD

**Issue by Polantaris** [gameboy9/DW4RandoHacker#75]
Using the below seed and flags, when I used a Wing of Wyvern to go to Lakanaba during Chapter 3 in a seed generated by version 2.0.4, it returned me to the middle of the ocean, softlocking the game. Screenshot: https://i.imgur.com/PN94zpA.png

I suspect this might be the original return point for Lakanaba, but I have no way to back that up right now. Also, I used a Wing of Wyvern earlier to return to Santeem at the end of Chapter 2 and it had no issues, so it's not like all return points are broken.

Seed: 58745490
Flags: t!B0z@CA51
https://i.imgur.com/Nbz44GX.png

**Comment by Polantaris** [comment]
I just realized this is probably the same issue as #69. Apologies, feel free to close if it is.

**Comment by gameboy9** [comment]
I don't think this is a duplicate... but I did fix this; it will be in the next release.
