### ISSUE TITLE
Two more Tempe bugs

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#78]
Seed: 1723006585
Flags: tI311bs200
(Also applies to the other two issues I submitted earlier)
I was able to walk around Tempe in this seed.  See screenshot below.  The north exit inside the town drops you off south of the town on the world map.

![image](https://user-images.githubusercontent.com/3443178/59109720-8cb79d80-890b-11e9-9ccd-65116ecc62f4.png)

Also, after beating the Humanoid, it took me to the north end of town.  Unsure if bug, intended, or non-issue, but I usually hit the inn and the item shop on the way out.

**Comment by gameboy9** [comment]
This should be fixed in the next release.
