### ISSUE TITLE
Allow for Small Medals to be Sold or Discarded

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#8]
Not a bug, would consider it an enhancement. Finding medals in earlier chapters (3 specifically) can clog up your inventory. It'd be cool if there was an option to allow them to be sold or dropped. Maybe they could only be found in Chapter 5 as normal, that'd work too.

**Comment by gameboy9** [comment]
I need to figure out where the pricing is in the ROM, as well as whether items can be sold or not.  But when I do... it's on!

**Comment by gameboy9** [comment]
This is good to go!  :)
