### ISSUE TITLE
Randomized Crested Vipers with Enemy Randomization Off?

### ISSUE THREAD

**Issue by TheCowness** [gameboy9/DW4RandoHacker#80]
Seed: 1723006585
Flags: tI311bs200
Flags are: Random enemy groups, random shops, random character locations, random map.  No random enemy stats or random enemy skills.  When I got to Saro's Shadow, he showed up with two Crested Vipers that could use Wings of Wyvern and cast Blaze.  I did not notice any other monsters use random skills in the seed, including the Razor Winds that showed up with Balzack.

Wonder if this is related to the 0.13.2 patch that tweaked which skills are available to enemies?  Is the Defense spell not an allowed early-boss skill?

**Comment by gameboy9** [comment]
I believe that Crested Viper was a monster in the Cave of Betrayal?  That fired off the "limit Cave Of Betrayal bosses to Level 2 moves only" code.  I added a check to only do this if randomize monster patterns is checked; that will be in the next release.
