### ISSUE TITLE
Empty combobox issue with flags

### ISSUE THREAD

**Issue by DanielPoissant** [gameboy9/DW4RandoHacker#88]
In some rare scenarios, the combobox are not filled to the defaut value when opening the application and causes a short flag sequence and issue with bosses on chapter 1, chapter 2 mid-boss and chapter 4 end-boss being absent from battle.

Included screenshot has shorter flags.

![Clipboard016](https://user-images.githubusercontent.com/50304426/77198824-1d87f000-6abe-11ea-967a-1a7b138f8d5d.jpg)

**Comment by DanielPoissant** [comment]
And voilà.

![dw4randobug](https://user-images.githubusercontent.com/50304426/77258144-13e1c200-6c4f-11ea-89d3-1cb66c55f7fe.jpg)

**Comment by gameboy9** [comment]
I believe this was fixed in recent versions.  Please reopen if there is still an issue.  Thanks!
