### ISSUE TITLE
Birdsong Nectar Acquired Twice In Chapter 2

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#9]
I found the Birdsong Nectar in Birdsong Tower after searching where the fairies leave it (as you would in a normal play-through) then found it again in the dresser in the old man's room in the back of Santeem. Seed information is as follows...

Seed - 1470868112

Options:

Random Chapter 1-4 Heroes
Random Chapter 5 Hero Acquisition
Random Monster Zones
Random Monster Stats - Light
Random Treasures
Random Stores
Random Hero Stats - Light
Random XP Gain
Random Gold Gain
Speed Up Battles

**Comment by gameboy9** [comment]
In my version, the game outright crashed!  It turns out there were TWO direct LDAs, and I picked the wrong one.  I have it fixed though, so that will be in the next version.
