### ISSUE TITLE
.exe Missing

### ISSUE THREAD

**Issue by Skelingaton** [gameboy9/DW4RandoHacker#91]
Looking through the files after downloading there is no .exe to run the randomizer.

**Comment by TheCowness** [comment]
You probably downloaded the source code. If you go to the main DW4RandoHacker page, there should be a "Releases" tab above the file list. If you go there, each release should have a separate exe download link.

**Comment by Skelingaton** [comment]
Well I feel like a dummy now.  Almost couldn't find the tab even after you mentioned it.
